// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package metadata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataServiceClient interface {
	GetVolumes(ctx context.Context, in *Node, opts ...grpc.CallOption) (*ResponseGetVolumes, error)
	AddMetadata(ctx context.Context, in *Metadata, opts ...grpc.CallOption) (*ResponseAddMetadata, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetVolumes(ctx context.Context, in *Node, opts ...grpc.CallOption) (*ResponseGetVolumes, error) {
	out := new(ResponseGetVolumes)
	err := c.cc.Invoke(ctx, "/alicefr.csi.pkg.qsd.MetadataService/GetVolumes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) AddMetadata(ctx context.Context, in *Metadata, opts ...grpc.CallOption) (*ResponseAddMetadata, error) {
	out := new(ResponseAddMetadata)
	err := c.cc.Invoke(ctx, "/alicefr.csi.pkg.qsd.MetadataService/AddMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility
type MetadataServiceServer interface {
	GetVolumes(context.Context, *Node) (*ResponseGetVolumes, error)
	AddMetadata(context.Context, *Metadata) (*ResponseAddMetadata, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetadataServiceServer struct {
}

func (UnimplementedMetadataServiceServer) GetVolumes(context.Context, *Node) (*ResponseGetVolumes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumes not implemented")
}
func (UnimplementedMetadataServiceServer) AddMetadata(context.Context, *Metadata) (*ResponseAddMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMetadata not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_GetVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alicefr.csi.pkg.qsd.MetadataService/GetVolumes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetVolumes(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_AddMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).AddMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alicefr.csi.pkg.qsd.MetadataService/AddMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).AddMetadata(ctx, req.(*Metadata))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alicefr.csi.pkg.qsd.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVolumes",
			Handler:    _MetadataService_GetVolumes_Handler,
		},
		{
			MethodName: "AddMetadata",
			Handler:    _MetadataService_AddMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/metadata/metadata.proto",
}
