# permissions for end users to view metadata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metadata-viewer-role
rules:
- apiGroups:
  - csi.qsd.csi.qsd
  resources:
  - metadata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csi.qsd.csi.qsd
  resources:
  - metadata/status
  verbs:
  - get
