# permissions for end users to edit metadata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metadata-editor-role
rules:
- apiGroups:
  - csi.qsd.csi.qsd
  resources:
  - metadata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.qsd.csi.qsd
  resources:
  - metadata/status
  verbs:
  - get
