apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: qsd-ds
  namespace: csi-qsd
spec:
  selector:
    matchLabels:
      name: qsd
  template:
    metadata:
      labels:
        name: qsd
    spec:
      containers:
      - name: qsd
        image: docker.io/qsd/qsd:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - protocol: TCP
          containerPort: 4444
          hostPort: 4444
        volumeMounts:
        - name: images
          mountPath: /var/lib/qsd/images
          mountPropagation: Bidirectional
        - name: sockets
          mountPath: /var/lib/qsd/sockets
          mountPropagation: Bidirectional
      volumes:
      - name: images
        hostPath:
          path: /var/run/qsd/images
          type: DirectoryOrCreate
      - name: sockets
        hostPath:
          path: /var/run/qsd/sockets
          type: DirectoryOrCreate
