apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-copy-from-snap
spec:
  storageClassName: csi-qsd
  dataSource:
    name: pvc-snapshot2 
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
