apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-copy-from-pvc
spec:
  storageClassName: csi-qsd
  dataSource:
    name: pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-pvc-copy-from-pvc
spec:
  containers:
    - name: my-container
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /pvc
          name: my-volume
      imagePullPolicy: IfNotPresent
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc-copy-from-pvc

